### ISSUE TITLE
Failure with error saying entrypoint.ps1 is not found

### ISSUE THREAD

**Issue by sheldonhull** [JustinGrote/Super-Duper-Linter#12]
## Description

I plugged this most excellent of super duper linters into a github action workflow without any alteration. The result failed with the error listed below.

```log
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./entrypoint.ps1": stat ./entrypoint.ps1: no such file or directory: unknown.
```

## Reproduce

The github action layout I used was similar to this: 

```yaml
name: 'Run Pull Request Update Checks'
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

defaults:
  run:
    shell: pwsh
    working-directory: .
jobs:
  github-pr:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        name: Auto Label
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: aslafy-z/conventional-pr-title-action@master
        name:  'Validate Title Adheres to Conventional Commit Format'
        with:
          success-state: Title follows the specification.
          failure-state: Title does not follow the specification.
          context-name: conventional-pr-title
          preset: conventional-changelog-angular@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-linting:
    name: 'Apply FMT & Scan For Secrets'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # don't use shallow fetch as I'm trying to commit and push back up changed files to the main
          # token: ${{ secrets.GITHUB_TOKEN }}
      - name: Super Duper Linter
        uses: JustinGrote/Super-Duper-Linter@preview
```
